I created a readme guide for articles/posts
opensourcedesign/opensourcedesign.github.io pull request #300
Opened 2020-09-03 09:26 UTC by Erioldoesdesign

Because it's not super clear what is needed. :)

2020-09-03 15:00 UTC, RDIL requested changes
Nice post!  Just a few minor tweaks that should be made.

2020-09-03 17:31 UTC, Erioldoesdesign commented on _posts/How-to-add-an-article-to-open-source-design.md
> +- Once finished, you can submit a pull request of your article/post. This will then be reviewed by two open source design community members and comments, changes may be requested before it is publish
Added the periods and removed 'repo'

2020-09-03 20:13 UTC, RDIL approved these changes

2020-09-10 17:20 UTC, vinitshahdeo approved these changes

2020-09-10 19:00 UTC, merged