Add scroll to top button
opensourcedesign/opensourcedesign.github.io pull request #364
Opened 2021-08-12 18:17 UTC by im-adithya

## Proposed changes (including videos or screenshots)
Added scroll to top button

https://user-images.githubusercontent.com/64399555/129247975-6769c9c0-9a4c-4a43-82bc-98ec5a490df7.mp4

## Issue(s)
Fixes #302

2021-08-12 18:18 UTC, im-adithya commented
@Erioldoesdesign please review :D

2021-08-29 01:49 UTC, Arhell submitted a review, later dismissed

2021-10-06 17:26 UTC, SaptakS requested changes

2021-10-06 17:26 UTC, SaptakS commented on _sass/_layout.scss
> +  right: 10%;
Let's fix this to 50px as well. The % doesn't scale very well in different screen sizes and sometimes it's a little too far inside.

2022-02-19 17:10 UTC, Erioldoesdesign commented
@im-adithya there are changes on this PR requested please 🙏

2022-02-20 09:40 UTC, im-adithya commented
Done! Sorry for the delay!

2022-02-20 10:00 UTC, Erioldoesdesign commented
@SaptakS ready for re-review!

2022-09-09 22:50 UTC, AliReza1083 reviewed
I reviewed your codes, It was written nice and clean.
wish you all the best.

2022-09-12 14:34 UTC, Erioldoesdesign commented
@SaptakS when you get a chance to look? have changes been made?

2022-09-12 18:41 UTC, SaptakS commented
Somehow missed the previous messages. Apologies! I will take a look and re-review.

2022-09-28 14:09 UTC, SaptakS approved these changes

2022-11-04 15:35 UTC, Erioldoesdesign approved these changes
LGTM - Let's merge it :)

2022-11-04 15:35 UTC, merged