update people folder links
opensourcedesign/opensourcedesign.github.io pull request #404
Opened 2022-10-24 06:33 UTC by Arhell

resolve https://github.com/opensourcedesign/opensourcedesign.github.io/issues/403

2022-10-24 16:23 UTC, RDIL requested changes
Why remove the presentations?

2022-10-25 22:17 UTC, Arhell commented
> Why remove the presentations?

my IDE tries to remove them, corrected

2022-10-26 00:16 UTC, RDIL approved these changes

2022-11-03 15:18 UTC, SaptakS approved these changes

2022-11-03 15:19 UTC, merged